import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, Hydrate } from '@tanstack/react-query';
import { dehydrate } from '@tanstack/react-query/hydration';
import { QueryClient } from '@tanstack/react-query';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Create a client
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
     const dehydratedState = dehydrate(queryClient);
  return (
  
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient} contextSharing={true}>
          <Hydrate state={dehydratedState}>{children}</Hydrate>
        </QueryClientProvider>
      </body>
    </html>
  );
}


